= Введение

Этот документ - попытка идентификации и обобщения проблем современных школьных учебников.
Под проблемами здесь понимаются не опечатки и прочие ошибки случайного характера, а
системные проблемы:

    * неполнота описания;
    * противоречивость;
    * двусмысленность;
    * чрезмерная сложность;
    * обилие второстепенных деталей;
    * недостаточный акцент на важном;
    * отсутствие определений в явном виде;
    * и т.п.

Эти системные проблемы:

* наносят значительный ущерб как качеству образовательного
  процесса так и здоровью учащися;
* делают комбинацию "учитель и набор учебных материалов" неполноценной, т.е.
  недостаточной для освоения учебной программы на должном уровне.
* снижают интерес к изучаемым предметам вплоть до полного их неприятия;
* требуют гораздо большего времени на изучение материала чем это необходимо.
  За счет этого у учащихся остается недостаточно времени для активного отдыха.

К сожалению, многие учителя не замечают перечисленных проблем либо не считают их
таковыми.
Недостатки обучения ученики вынуждены компенсировать активной помощью родителей
и репетиторов.

Целью документа ни в коем случае не является попытка дискредитировать государственную
систему образования.
Цель документа - помощь в улучшении качества учебных материалов.






