= Введение

Этот документ - попытка идентификации и обобщения проблем современных школьных учебников.

Целью документа НЕ является попытка дискредитировать государственную систему
образования.
Цель документа - выявить и обобщить конкретные проблемы и посодействовать в
улучшении качества учебных материалов.

Под проблемами здесь понимаются не опечатки и прочие случайные ошибки, а
проблемы системного характера:

    * неполнота описания;
    * противоречивость;
    * двусмысленность;
    * чрезмерная сложность;
    * обилие второстепенных деталей;
    * недостаточный акцент на важном;
    * отсутствие определений в явном виде;
    * и т.п.

Эти системные проблемы влекут за в свою очередь следующие проблемы:

* наносят значительный ущерб качеству образовательного процесса;
* делают комбинацию "учитель и набор учебных материалов" неполноценной, т.е.
  недостаточной для освоения учебной программы на должном уровне;
* снижают интерес к изучаемым предметам вплоть до полного их неприятия;
* требуют гораздо большего времени на изучение материала чем это необходимо.
  За счет этого у учащихся остается недостаточно времени для активного отдыха;
  Как следствие, страдает здоровье учащихся.

К сожалению, многие учителя не замечают перечисленных проблем либо не считают их
таковыми.
Отношение некоторых учителей к данной проблеме хорошо отражает следующая реплика
одного учителя на попытку автора пообщаться на эту тему: "Все там
понятно, надо внимательно читать!".
Безусловно, читать надо внимательно, но ведь системные проблемы в учебнике
вниманием не исправить.
Опытные преподаватели вынуждены использовать альтернативные учебники, учебники
советского периода и прочие, более надежные источники знаний.

Недостатки обучения ученики вынуждены компенсировать активной помощью родителей
и наймом репетиторов.
Внимание учеников, образно говоря, "сжигается" неэффективными, чрезмерно сложными
материалами.
Доходит до абсурда, когда репетиторов нанимают ученикам начальной школы!

Считаем, что вопрос с учебыми материалами стратегически важен.
Опиcанные выше проблемы ставят наших детей в невыгодное положение и лишает их, а
значит и всех нас, конкурентного преимущества в научной сфере.
Вопрос важен настолько, что мы не имеем права просто назначить составителей и
рецензентов учебных пособий и надеятся на хорошо сделанную работу.
Мы обязаны собрать все самое лучшее, что существует на данный момент и
выдать максимально качественные материалы, коих достаточно, особенно в сфере
точных и естественных наук.
Если нет средств, сил или специалистов - вернуться к наиболее удачным изданиям.
При этм необходимо руководствоваться не объемом, а качеством материалов.







